### ISSUE TITLE
Import YAML modules, not just binaries

### ISSUE THREAD

**Issue by codephi** [phlowdotdev/phlow#9]
Currently, only binary modules are allowed to be imported.
With issue #8  resolved, it is now possible to import YAML modules, when the phlow.yaml file indicates that the package's `main` is a YAML file.

## Example `phlow.yaml`:

```yaml
name: echo
main: ./my_steps.yaml  # this or module.so to binary
description: Echo a message.
version: 0.0.1
author: Philippe Assis <codephilippe@gmail.com>
repository: https://github.com/lowcarboncode/phlow
license: MIT
type: step
tags:
  - echo
input:
  !root:
    type: any
    description: The message to echo.
    required: true
    default: null
```

The YAML file referenced by `main` must not contain a `main` field itself.
This means only Phlow modules of type step can be imported as YAML modules.
Inside this YAML module, it is still possible to import other modules.

## Example `my_steps.yaml`:
```yaml
modules: #Modules like main do not work here
  - module: log
    version: latest
  - module: ./my_module.so
    name: my_module

steps:
  - use: log
    input:
      message: input.message
  - use: my_module
    input: # ...
```

The parameters passed by the main step are received by the YAML module via the `input.*` object.
The `input` follows the definition provided in the `phlow.yaml` file, including its `output`.

Both `input` and `output` fields are validated at runtime.

Imported YAML modules must be executed in separate threads, and not within the same thread as the main steps—just like binary modules are currently executed.

This change will require a significant update to the main.rs of the runtime to support isolated thread execution for YAML-based modules.
